spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver 

#JPA Settings
  jpa:
    hibernate:
      ddl_auto: update